### ISSUE TITLE
追加課題

### ISSUE THREAD

**Issue by nari** [kakobq/pachimon#22]
## スレッド検索機能
スレッドの検索機能を実装したい
- スレッドタイトルの検索
- コメントの検索
をそれぞれ(もしくは一つのFormで)一覧に実装する

## スレッドコメントの返信
返信をできるようにしたい。
コメントは基本的に日時順になるが、返信をしたらそのコメントのすぐ下に返信コメントとして表示したい。

## 自動デプロイ
特定のブランチにmerge（rootブランチが良い）されたら、自動テストしてデプロイできるようにしたい
つまりこれ: https://github.com/kakobq/pachimon/issues/7

**Comment by kakobq** [comment]
#21 スレッド実装
#24 スレッド検索
#25 コメント返信
